[746] Add student tests stats
AdeptLMS/lingutest_client pull request #2
Opened 2023-02-13 20:11 UTC by skrix

Related PRs:

- test.lingu.com - https://github.com/AdeptLMS/lingutest/pull/529
- app.lingu.com - https://github.com/AdeptLMS/lingu/pull/2851

2023-02-20 22:08 UTC, AnatoliiD requested changes

2023-02-20 22:08 UTC, AnatoliiD commented on lib/lingutest_client/api/operations/list.rb
> +          select
Nice improvement!
Can you please sort method names in alphabet order, delegate methods like `.reject` and `.first`, and remove `.present?` as it is part of `activesupport` which is not listed in gem dependencies?

2023-02-20 22:09 UTC, AnatoliiD commented on lib/lingutest_client/api/operations/list.rb
> +          select
You can always delegate `.empty?` 😃

2023-02-21 05:36 UTC, skrix commented on lib/lingutest_client/api/operations/list.rb
> +          select
of course, nice comment thx!)

2023-03-08 09:05 UTC, merged